spring:
  application:
    name: infinity
logging:
  level:
    org.springframework: DEBUG
    com.infinity: DEBUG
couchbase-doc-maintainer:
  user-management:
    user-resource:
      classIdValue: 1000
      initialValue: 1000
  accountManagement:
    customerResource:
      classIdValue: 2000
      initialValue: 1000
  orderManagement:
    orderResource:
      classIdValue: 3000
      initialValue: 1000
  productCatalog:
    productResource:
      classIdValue: 4000
      initialValue: 1000